// End-to-end tests for issue #191 — the ConvertTTFToWOFF2 entry point.
//
// Reads TTF fixtures generated by generate_fixtures.py (valid_baseline.ttf,
// non_monotonic_endpts.ttf, ...) and checks that ConvertTTFToWOFF2:
//   * succeeds on a legitimate TTF, and
//   * rejects (returns false, promptly, without huge allocations) every
//     crafted input that previously triggered the uint16_t wraparound
//     described in PLAN.md section 1.
//
// Fixtures are located via the WOFF2_FIXTURE_DIR environment variable when
// set, otherwise via argv[1].  This keeps the test invokable both from
// ctest (which passes the build-time fixture directory) and by hand.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

#include <woff2/encode.h>

namespace {

int g_total = 0;
int g_failed = 0;

#define CHECK_MSG(cond, msg)                                                   \
  do {                                                                         \
    if (!(cond)) {                                                             \
      std::fprintf(stderr, "  FAIL: %s:%d: %s — %s\n", __FILE__, __LINE__,     \
                   #cond, msg);                                                \
      ++g_failed;                                                              \
      return;                                                                  \
    }                                                                          \
  } while (0)

bool ReadFile(const std::string& path, std::vector<uint8_t>* out) {
  std::ifstream f(path, std::ios::binary);
  if (!f) return false;
  f.seekg(0, std::ios::end);
  std::streamsize n = f.tellg();
  f.seekg(0, std::ios::beg);
  out->resize(static_cast<size_t>(n));
  if (n > 0) f.read(reinterpret_cast<char*>(out->data()), n);
  return static_cast<bool>(f);
}

// Returns woff2's return value for the given input, using brotli_quality=1
// to keep the test fast.  The output buffer is sized per MaxWOFF2CompressedSize
// but capped at 32 MiB to contain any allocation damage if the fix regresses.
bool RunEncoder(const std::vector<uint8_t>& input, size_t* out_size_bytes) {
  size_t cap = woff2::MaxWOFF2CompressedSize(input.data(), input.size());
  const size_t kHardCap = 32 * 1024 * 1024;
  if (cap > kHardCap) cap = kHardCap;
  if (cap < 1024) cap = 1024;
  std::vector<uint8_t> out(cap);
  size_t out_size = out.size();
  woff2::WOFF2Params params;
  params.brotli_quality = 1;
  bool ok = woff2::ConvertTTFToWOFF2(input.data(), input.size(),
                                     out.data(), &out_size, params);
  if (out_size_bytes) *out_size_bytes = ok ? out_size : 0;
  return ok;
}

std::string g_fixture_dir;

std::string FixturePath(const char* name) {
  std::string path = g_fixture_dir;
  if (!path.empty() && path.back() != '/') path.push_back('/');
  path.append(name);
  return path;
}

// Tests -----------------------------------------------------------------------

#define TEST(name)                                                             \
  void name();                                                                 \
  void Run_##name() {                                                          \
    ++g_total;                                                                 \
    std::fprintf(stderr, "[RUN ] %s\n", #name);                                \
    int before = g_failed;                                                     \
    name();                                                                    \
    if (g_failed == before) std::fprintf(stderr, "[ OK ] %s\n", #name);        \
  }                                                                            \
  void name()

// Sanity: the fixture builder must produce a font that actually encodes.
// If this fails, the remaining assertions cannot be interpreted (we can't
// tell "rejected due to bug fix" from "rejected due to bad fixture").
TEST(EncodesValidBaseline) {
  std::vector<uint8_t> input;
  CHECK_MSG(ReadFile(FixturePath("valid_baseline.ttf"), &input),
            "failed to read valid_baseline.ttf");
  CHECK_MSG(!input.empty(), "valid_baseline.ttf is empty");
  size_t written = 0;
  bool ok = RunEncoder(input, &written);
  CHECK_MSG(ok, "legitimate TTF must compress");
  CHECK_MSG(written > 0, "compressed output must be non-empty");
}

// Primary regression test: the exact endPts == [5, 2] case from PLAN.md 5.3.
TEST(RejectsNonMonotonicEndpts) {
  std::vector<uint8_t> input;
  CHECK_MSG(ReadFile(FixturePath("non_monotonic_endpts.ttf"), &input),
            "failed to read non_monotonic_endpts.ttf");
  bool ok = RunEncoder(input, nullptr);
  CHECK_MSG(!ok, "TTF with non-monotonic endPts must be rejected");
}

// Smallest wrap: point_index < last_point_index by exactly one.
TEST(RejectsOneStepDown) {
  std::vector<uint8_t> input;
  CHECK_MSG(ReadFile(FixturePath("non_monotonic_one_step.ttf"), &input),
            "failed to read non_monotonic_one_step.ttf");
  bool ok = RunEncoder(input, nullptr);
  CHECK_MSG(!ok, "endPts [1,0] must be rejected");
}

// Extreme downward drop from near-max to zero.
TEST(RejectsLargeDrop) {
  std::vector<uint8_t> input;
  CHECK_MSG(ReadFile(FixturePath("non_monotonic_large_drop.ttf"), &input),
            "failed to read non_monotonic_large_drop.ttf");
  bool ok = RunEncoder(input, nullptr);
  CHECK_MSG(!ok, "endPts [0xFFFE,0] must be rejected");
}

// The DoS reproducer — many crafted glyphs, each wrapping.  Before the fix
// this would allocate multi-GB of std::vector<Point> storage; after the fix
// it must return false within a few milliseconds.
TEST(RejectsDosReproducer) {
  std::vector<uint8_t> input;
  CHECK_MSG(ReadFile(FixturePath("dos_reproducer.ttf"), &input),
            "failed to read dos_reproducer.ttf");
  bool ok = RunEncoder(input, nullptr);
  CHECK_MSG(!ok, "DoS reproducer must be rejected");
}

// Valid arithmetic, physically impossible: num_points = 0xFFFF but the glyph
// record is only a few hundred bytes.  Belt-and-braces check (PLAN 3.2)
// must reject this.
TEST(RejectsOversizedEndpoint) {
  std::vector<uint8_t> input;
  CHECK_MSG(ReadFile(FixturePath("large_endpoint.ttf"), &input),
            "failed to read large_endpoint.ttf");
  bool ok = RunEncoder(input, nullptr);
  CHECK_MSG(!ok, "endPts [0xFFFE,0xFFFF] with tiny glyph record must be "
                 "rejected by the buffer-bound check");
}

// Robustness: arbitrary short junk must be rejected cleanly (not crash, not
// OOM).  Establishes that ConvertTTFToWOFF2 has sensible behaviour on garbage.
TEST(RejectsGarbageInput) {
  std::vector<uint8_t> junk(128, 0xAB);
  bool ok = RunEncoder(junk, nullptr);
  CHECK_MSG(!ok, "garbage input must be rejected");
}

// Robustness: empty input.
TEST(RejectsEmptyInput) {
  std::vector<uint8_t> empty;
  bool ok = RunEncoder(empty, nullptr);
  CHECK_MSG(!ok, "empty input must be rejected");
}

}  // namespace

int main(int argc, char** argv) {
  const char* env = std::getenv("WOFF2_FIXTURE_DIR");
  if (env && *env) {
    g_fixture_dir = env;
  } else if (argc > 1) {
    g_fixture_dir = argv[1];
  } else {
    g_fixture_dir = ".";
  }
  std::fprintf(stderr, "fixture dir: %s\n", g_fixture_dir.c_str());

  Run_EncodesValidBaseline();
  Run_RejectsNonMonotonicEndpts();
  Run_RejectsOneStepDown();
  Run_RejectsLargeDrop();
  Run_RejectsDosReproducer();
  Run_RejectsOversizedEndpoint();
  Run_RejectsGarbageInput();
  Run_RejectsEmptyInput();

  std::fprintf(stderr, "\n%d/%d tests passed\n", g_total - g_failed, g_total);
  return g_failed == 0 ? 0 : 1;
}
